### ISSUE TITLE
如何将图片压缩到指定大小？

### ISSUE THREAD

**Issue by jayleco** [nanchen2251/CompressHelper#17]
例如我想将一张原图大小为540*5678，如果指定将他等比压缩为720*75701；设置使用
.setMaxWidth(720).setMaxHeight(75701)这两个参数压缩完查看尺寸并没有压缩到我要的这个尺寸。

请问作者我该如何达到我的需求呢？

**Comment by nanchen2251** [comment]
本库暂时没有此项功能
