### ISSUE TITLE
Rxjava 1.x, 2.x 冲突

### ISSUE THREAD

**Issue by stormlei** [nanchen2251/CompressHelper#18]
看代码中并未用到Rx，Rx普遍已经更新到2.x，引入该库会冲突，请要么去掉Rx，要么请更新到2.x。 @nanchen2251

**Comment by nanchen2251** [comment]
这个问题收到了，之前想把Rx带入的，但现在没有时间来编写，那如你们所愿，先去掉，马上就更新。谢谢提醒了，
