### ISSUE TITLE
能否增加选项配置：可以设定文件大小呢？

### ISSUE THREAD

**Issue by stormlei** [nanchen2251/CompressHelper#2]
@nanchen2251

**Comment by nanchen2251** [comment]
这个后面会考虑的

**Comment by XYScience** [comment]
同一，比如压缩后的文件小于100k

**Comment by nanchen2251** [comment]
这个后面根据大家需要，我会考虑增加接口，不过对于这种方式其实我是不推荐的，因为有的文件压缩到100k以下会相当模糊。但其实我们大多数图片直接默认的压缩下来都是50-80k的

**Comment by 354420603** [comment]
很多情况下还是需要指定压缩的大小的，比如说我们公司超过64k后台就不允许上传
