### ISSUE TITLE
压缩后size为0

### ISSUE THREAD

**Issue by s1168805219** [nanchen2251/CompressHelper#21]
点击压缩后，size显示为0，也没有报错或toast提示错误。我把`app module`中的`build.gradle`的`targetSdkVersion` 改成22就可以了，23,24,25都不行，设置里面权限也给了。最后发现注释掉`.setDestinationDirectoryPath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).getAbsolutePath())`就可以了

**Comment by nanchen2251** [comment]
所以，注释掉这句话 23,24,25都可以了吗？

**Comment by s1168805219** [comment]
注释掉的是.setDestinationDirectoryPath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES).getAbsolutePath())就可以了

**Comment by lovelyelfpop** [comment]
sd卡要单独向用户申请权限的吧，你看NovaLauncher在备份的时候，就会询问申请sd卡权限
