### ISSUE TITLE
如何一次压缩多张图片

### ISSUE THREAD

**Issue by zhangchaoxu** [nanchen2251/CompressHelper#3]

**Comment by nanchen2251** [comment]
可以直接用一个循环压缩。比如
 for (int i = 0; i < selImageList.size(); i++) {

            String filePath = selImageList.get(i).path;

            final File oldFile = new File(filePath);
            File newFile = null;
            try {
                newFile = mCompressor.compressToFile(oldFile);
                LogUtils.e(TAG, String.format(Locale.CHINA, "第%d张，压缩前Size : %s", i, getReadableFileSize
                        (oldFile.length())));
                LogUtils.e(TAG, String.format(Locale.CHINA, "第%d张，压缩后Size : %s", i, getReadableFileSize
                        (newFile.length())));
                mFiles.add(newFile);
            } catch (Exception e) {
                errorNum++;
                e.printStackTrace();
            }
}

**Comment by zhangchaoxu** [comment]
Thanks
