### ISSUE TITLE
两个小问题

### ISSUE THREAD

**Issue by zhouzidan** [nanchen2251/CompressHelper#4]
问题一
options.inSampleSize = calculateInSampleSize(options, actualWidth, actualHeight);
这里options里面的宽度和高度可能没有值，你需要再次设值
        if (actualWidth > 0 && actualHeight > 0) {
            options.outHeight = actualHeight;
            options.outWidth = actualWidth;
        }
问题二
bitmap2这个对象没有调用recycle()

**Comment by nanchen2251** [comment]
谢谢指出。我有空了看一下。

**Comment by nanchen2251** [comment]
bitmap不需要recycle，
因为我添加了
options.inPurgeable = true;
ptions.inInputShareable = true;
