### ISSUE TITLE
加库之后拍照返回有问题

### ISSUE THREAD

**Issue by mishaoshuai** [nanchen2251/CompressHelper#40]
加上本库之后，调用相机拍照，第一次能返回，走onactivityresult，但是，再调用相机拍照，拍完照之后选择确定，就不回去了，选取消才能返回，确定是回不去的，不知为何

**Comment by mishaoshuai** [comment]
找到问题，我自己代码问题，多有打扰

**Comment by nanchen2251** [comment]
对的，正如我群里所说的，CompressHelper 不会去干预你的拍照功能，也不关心。
