### ISSUE TITLE
使用该工具必须使用RxJava。怎么修改代码，可以不使用RxJava?

### ISSUE THREAD

**Issue by MagicKim** [nanchen2251/CompressHelper#5]

**Comment by nanchen2251** [comment]
代码中的确是提供了RxJava的接口，但是目前还存在些许问题，尚未解决。你可以import该module自己注释掉RxJava相关代码，去除引用即可。不过我很意外的是，哪里规定了必须使用RxJava了？

**Comment by MagicKim** [comment]
我是看到了CompressHelper.java这个类里面使用了RxJava.

**Comment by nanchen2251** [comment]
额，那没关系的，这里面的使用是为了支持RxJava方式的调用，并不会影响你们的正常使用的。实际上你可查看源码，发现正常的调用是用的建造者模式。并没有走Rx的逻辑的。

**Comment by MagicKim** [comment]
好的，谢谢！
